before:
  hooks:
  - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
    - amd64

archives:
  - name_template: '{{ .ProjectName }}-{{ .Tag }}-{{ .Os }}-{{ replace .Os "windows" "win32" }}'  # Use name_template with replace functionality
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
